#!/bin/sh
module="bsl"
device="bsl_ctl"
mode="664"

/sbin/insmod $module.ko $* || exit 1

rm -f /dev/${device}
rm -f /dev/${device}-[1-3]

major=$(awk "\$2==\"$device\" {print \$1}" /proc/devices)

mknod /dev/${device} c $major 0
mknod /dev/${device}-1 c $major 1
mknod /dev/${device}-2 c $major 2
mknod /dev/${device}-3 c $major 3

